### ISSUE TITLE
Pearl with Pidgin 2.0.11?

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [adriankeenan/pidgin-toast-8#3]
Is there any new Pearl version to use with Pidgin 2.0.11?

**Comment by adriankeenan** [comment]
Hi, I don't know because I don't actually use this plugin anymore. Does the plugin not work with the Perl runtimes linked in the readme on new pidgin versions?

**Comment by ZatsuneNoMokou** [comment]
Dunno, just I try to avoid installing program that seems to be... "out-to-date"
